import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Topbar from "./components/topbar";
import Providers from "./providers";


const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={geist.className}>
        <Providers>
          <Topbar />
          {children}
        </Providers>
      </body>
    </html >
  );
}
